import json, re
from pathlib import Path

bases = [
('Panca piana con bilanciere','petto',['Petto','Tricipiti','Deltoide anteriore'],'Bilanciere','Panca'),
('Panca inclinata con bilanciere','petto',['Petto alto','Tricipiti','Deltoide anteriore'],'Bilanciere','Panca'),
('Panca declinata con bilanciere','petto',['Petto','Tricipiti'],'Bilanciere','Panca'),
('Panca piana con manubri','petto',['Petto','Tricipiti','Deltoide anteriore'],'Manubri','Panca'),
('Panca inclinata con manubri','petto',['Petto alto','Tricipiti','Deltoide anteriore'],'Manubri','Panca'),
('Floor press con manubri','petto',['Petto','Tricipiti'],'Manubri','Spinta'),
('Floor press con bilanciere','petto',['Petto','Tricipiti'],'Bilanciere','Spinta'),
('Chest press orizzontale','petto',['Petto','Tricipiti','Deltoide anteriore'],'Macchina','Macchina'),
('Chest press inclinata','petto',['Petto alto','Tricipiti','Deltoide anteriore'],'Macchina','Macchina'),
('Pec deck','petto',['Petto','Deltoide anteriore'],'Macchina','Macchina'),
('Croci ai cavi alte','petto',['Petto','Deltoide anteriore'],'Cavi','Isolamento'),
('Croci ai cavi basse','petto',['Petto alto','Deltoide anteriore'],'Cavi','Isolamento'),
('Croci ai cavi altezza petto','petto',['Petto'],'Cavi','Isolamento'),
('Croci con manubri su panca piana','petto',['Petto'],'Manubri','Isolamento'),
('Croci con manubri su panca inclinata','petto',['Petto alto'],'Manubri','Isolamento'),
('Push-up classico','petto',['Petto','Tricipiti','Core'],'Corpo libero','Corpo libero'),
('Push-up inclinato','petto',['Petto','Tricipiti'],'Corpo libero','Corpo libero'),
('Push-up declinato','petto',['Petto alto','Tricipiti'],'Corpo libero','Corpo libero'),
('Push-up presa stretta','petto',['Petto','Tricipiti'],'Corpo libero','Corpo libero'),
('Dip alle parallele','petto',['Petto','Tricipiti','Deltoide anteriore'],'Corpo libero','Corpo libero'),
('Trazioni prone','schiena',['Gran dorsale','Bicipiti','Core'],'Corpo libero','Trazione'),
('Trazioni supine','schiena',['Gran dorsale','Bicipiti'],'Corpo libero','Trazione'),
('Trazioni presa neutra','schiena',['Gran dorsale','Bicipiti'],'Corpo libero','Trazione'),
('Lat machine avanti','schiena',['Gran dorsale','Bicipiti'],'Macchina','Trazione'),
('Lat machine presa stretta','schiena',['Gran dorsale','Bicipiti'],'Macchina','Trazione'),
('Lat machine presa larga','schiena',['Gran dorsale','Bicipiti'],'Macchina','Trazione'),
('Lat machine supina','schiena',['Gran dorsale','Bicipiti'],'Macchina','Trazione'),
('Pulldown a braccia tese ai cavi','schiena',['Gran dorsale','Grande rotondo'],'Cavi','Isolamento'),
('Rematore con bilanciere','schiena',['Dorsali','Trapezio','Bicipiti'],'Bilanciere','Rematore'),
('Rematore Pendlay','schiena',['Dorsali','Trapezio','Bicipiti'],'Bilanciere','Rematore'),
('Rematore con manubrio','schiena',['Gran dorsale','Trapezio','Bicipiti'],'Manubrio','Rematore'),
('Rematore chest-supported','schiena',['Dorsali','Trapezio','Bicipiti'],'Panca + manubri','Rematore'),
('Rematore macchina convergente','schiena',['Dorsali','Trapezio','Bicipiti'],'Macchina','Macchina'),
('Seated cable row','schiena',['Dorsali','Romboidi','Bicipiti'],'Cavi','Rematore'),
('Seated cable row presa stretta','schiena',['Dorsali','Romboidi','Bicipiti'],'Cavi','Rematore'),
('Seated cable row presa larga','schiena',['Romboidi','Trapezio','Dorsali'],'Cavi','Rematore'),
('T-bar row','schiena',['Dorsali','Trapezio','Bicipiti'],'Bilanciere','Rematore'),
('Pullover con manubrio','schiena',['Gran dorsale','Petto'],'Manubri','Isolamento'),
('Pullover ai cavi','schiena',['Gran dorsale'],'Cavi','Isolamento'),
('Face pull','spalle',['Deltoide posteriore','Trapezio','Romboidi'],'Cavi','Tirata'),
('Reverse fly ai cavi','spalle',['Deltoide posteriore','Romboidi'],'Cavi','Isolamento'),
('Reverse fly macchina','spalle',['Deltoide posteriore','Romboidi'],'Macchina','Macchina'),
('Alzate laterali con manubri','spalle',['Deltoide laterale'],'Manubri','Isolamento'),
('Alzate laterali ai cavi','spalle',['Deltoide laterale'],'Cavi','Isolamento'),
('Alzate laterali macchina','spalle',['Deltoide laterale'],'Macchina','Macchina'),
('Alzate laterali inclinate','spalle',['Deltoide laterale'],'Manubri','Isolamento'),
('Military press con bilanciere','spalle',['Deltoide anteriore','Tricipiti'],'Bilanciere','Spinta'),
('Shoulder press macchina','spalle',['Deltoide anteriore','Tricipiti'],'Macchina','Macchina'),
('Shoulder press con manubri','spalle',['Deltoide anteriore','Tricipiti'],'Manubri','Spinta'),
('Arnold press','spalle',['Deltoide anteriore','Deltoide laterale','Tricipiti'],'Manubri','Spinta'),
('Landmine press','spalle',['Deltoide anteriore','Tricipiti','Core'],'Landmine','Spinta'),
('Alzate frontali ai cavi','spalle',['Deltoide anteriore'],'Cavi','Isolamento'),
('Alzate frontali con manubri','spalle',['Deltoide anteriore'],'Manubri','Isolamento'),
('Curl con bilanciere','braccia',['Bicipite','Brachiale'],'Bilanciere','Flessione gomito'),
('Curl con EZ','braccia',['Bicipite','Brachiale'],'Bilanciere EZ','Flessione gomito'),
('Curl con manubri alternato','braccia',['Bicipite','Brachiale'],'Manubri','Flessione gomito'),
('Curl su panca inclinata','braccia',['Bicipite'],'Manubri','Flessione gomito'),
('Curl preacher','braccia',['Bicipite'],'Panca preacher','Isolamento'),
('Curl preacher macchina','braccia',['Bicipite'],'Macchina','Macchina'),
('Hammer curl','braccia',['Brachiale','Brachioradiale','Bicipite'],'Manubri','Flessione gomito'),
('Hammer curl ai cavi','braccia',['Brachiale','Brachioradiale'],'Cavi','Flessione gomito'),
('Bayesian curl ai cavi','braccia',['Bicipite'],'Cavi','Isolamento'),
('Curl ai cavi bassi','braccia',['Bicipite'],'Cavi','Isolamento'),
('Pushdown al cavo','braccia',['Tricipite'],'Cavi','Estensione gomito'),
('Pushdown con corda','braccia',['Tricipite'],'Cavi','Estensione gomito'),
('Pushdown presa inversa','braccia',['Tricipite'],'Cavi','Estensione gomito'),
('French press con EZ','braccia',['Tricipite'],'Bilanciere EZ','Estensione gomito'),
('Skull crusher','braccia',['Tricipite'],'Bilanciere EZ','Estensione gomito'),
('Estensione tricipiti sopra testa ai cavi','braccia',['Tricipite'],'Cavi','Estensione gomito'),
('Estensione tricipiti sopra testa con manubrio','braccia',['Tricipite'],'Manubrio','Estensione gomito'),
('Dip panca','braccia',['Tricipite','Petto'],'Corpo libero','Corpo libero'),
('Squat con bilanciere','gambe',['Quadricipite','Glutei','Adduttori'],'Bilanciere','Squat'),
('Front squat','gambe',['Quadricipite','Glutei','Core'],'Bilanciere','Squat'),
('Box squat','gambe',['Glutei','Quadricipite'],'Bilanciere','Squat'),
('Hack squat','gambe',['Quadricipite','Glutei'],'Macchina','Squat'),
('Hack squat piedi alti','gambe',['Glutei','Femorali'],'Macchina','Squat'),
('Leg press 45°','gambe',['Quadricipite','Glutei'],'Macchina','Pressa'),
('Leg press piedi alti','gambe',['Glutei','Femorali'],'Macchina','Pressa'),
('Leg press unilaterale','gambe',['Quadricipite','Glutei'],'Macchina','Pressa'),
('Bulgarian split squat','gambe',['Glutei','Quadricipite'],'Manubri','Unilaterale'),
('Affondo camminato','gambe',['Glutei','Quadricipite'],'Manubri','Unilaterale'),
('Reverse lunge','gambe',['Glutei','Quadricipite'],'Manubri','Unilaterale'),
('Step-up','gambe',['Glutei','Quadricipite'],'Manubri','Unilaterale'),
('Hip thrust con bilanciere','glutei',['Grande gluteo','Femorali'],'Bilanciere','Estensione anca'),
('Hip thrust macchina','glutei',['Grande gluteo','Femorali'],'Macchina','Macchina'),
('Glute bridge','glutei',['Grande gluteo'],'Corpo libero','Estensione anca'),
('Glute bridge con bilanciere','glutei',['Grande gluteo'],'Bilanciere','Estensione anca'),
('Cable pull-through','glutei',['Grande gluteo','Femorali'],'Cavi','Estensione anca'),
('Kickback ai cavi','glutei',['Grande gluteo'],'Cavi','Isolamento'),
('Abduzione macchina','glutei',['Gluteo medio','Gluteo piccolo'],'Macchina','Abduzione'),
('Abduzione ai cavi','glutei',['Gluteo medio','Gluteo piccolo'],'Cavi','Abduzione'),
('Romanian deadlift con bilanciere','femorali',['Femorali','Grande gluteo','Erettori spinali'],'Bilanciere','Hip hinge'),
('Romanian deadlift con manubri','femorali',['Femorali','Grande gluteo'],'Manubri','Hip hinge'),
('Stacco gambe tese','femorali',['Femorali','Glutei'],'Bilanciere','Hip hinge'),
('Leg curl sdraiato','femorali',['Femorali'],'Macchina','Flessione ginocchio'),
('Leg curl seduto','femorali',['Femorali'],'Macchina','Flessione ginocchio'),
('Leg curl unilaterale','femorali',['Femorali'],'Macchina','Flessione ginocchio'),
('Nordic curl assistito','femorali',['Femorali'],'Corpo libero','Flessione ginocchio'),
('Calf raise in piedi','polpacci',['Gastrocnemio','Soleo'],'Macchina','Flessione plantare'),
('Calf raise seduto','polpacci',['Soleo','Gastrocnemio'],'Macchina','Flessione plantare'),
('Calf raise alla leg press','polpacci',['Gastrocnemio','Soleo'],'Macchina','Flessione plantare'),
('Tibialis raise','polpacci',['Tibiale anteriore'],'Corpo libero','Dorsiflessione'),
('Crunch ai cavi','addome',['Retto addominale'],'Cavi','Flessione tronco'),
('Cable crunch in ginocchio','addome',['Retto addominale'],'Cavi','Flessione tronco'),
('Hanging knee raise','addome',['Retto addominale','Flessori anca'],'Sbarra','Core'),
('Hanging leg raise','addome',['Retto addominale','Flessori anca'],'Sbarra','Core'),
('Ab wheel rollout','addome',['Retto addominale','Core'],'Ruota addominale','Anti-estensione'),
('Plank','addome',['Core','Retto addominale'],'Corpo libero','Isometrico'),
('Side plank','addome',['Obliqui','Core'],'Corpo libero','Isometrico'),
]

variants=[
('standard','Esecuzione standard con tecnica controllata.'),
('pausa','Inserisci una pausa di 1–2 secondi nel punto di massima tensione.'),
('tempo lento','Usa un eccentrico controllato di circa 3 secondi.'),
('unilaterale','Esegui il movimento un lato alla volta mantenendo il controllo.'),
('presa neutra','Usa una presa neutra quando l’attrezzatura lo permette.'),
('presa larga','Usa una presa leggermente più larga quando biomeccanicamente naturale.'),
]

out=[]
for idx,(name,part,muscles,equipment,category) in enumerate(bases):
    for vi,(tag,variant_note) in enumerate(variants):
        # avoid awkward variants for inherently unilateral/bodyweight movements
        if tag=='unilaterale' and ('unilaterale' in name.lower() or 'plank' in name.lower() or 'nordic' in name.lower()):
            continue
        eid=f'iron-local-{idx+1:03d}-{vi+1:02d}'
        vname=name if tag=='standard' else f'{name} — {tag}'
        primary=muscles[0]
        instructions=[
            f'Prepara {equipment.lower()} e imposta una posizione stabile, neutra e confortevole.',
            f'Esegui {vname.lower()} con il focus sul distretto principale: {primary.lower()}.',
            variant_note,
            'Completa la fase concentrica senza slanci e controlla il ritorno alla posizione iniziale.',
            'Interrompi la serie se la tecnica si deteriora e scegli un carico gestibile.'
        ]
        tips=['Movimento controllato e ROM compatibile con la tua mobilità.','Mantieni il carico sotto controllo per tutta la ripetizione.','Regola carico, ROM e variante in base al livello e all’attrezzatura disponibile.']
        out.append({
            'id':eid,'exerciseId':eid,'name':vname,'source':'IronTrack Curated','bodyParts':[part],
            'targetMuscles':muscles[:1],'secondaryMuscles':muscles[1:],'equipments':[equipment],
            'exerciseType':'STRENGTH' if part!='addome' else 'CORE','category':category,'difficulty':'intermediate',
            'overview':f'{vname}: variante organizzata per allenare {primary.lower()} con {equipment.lower()}. Scheda editoriale IronTrack.',
            'description':f'Esercizio focalizzato su {", ".join(muscles).lower()}, con attenzione a controllo, stabilità e progressione.',
            'instructions':instructions,'exerciseTips':tips,'variations':[name],
            'keywords':[name,primary,part,equipment,tag,'IronTrack']
        })

Path(__file__).with_name('exercises_local.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print('generated',len(out))
